services:
  - type: web
    name: radiix-tracker
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    dockerCommand: php-fpm
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
    healthCheckPath: /up
    region: oregon
    plan: starter

databases:
  - name: radiix-tracker-db
    databaseName: radiix_tracker
    user: radiix_user
    plan: starter
